#!/usr/bin/env bash

set -euxo pipefail

repo_dir="$HOME/.dotfiles"

if [[ $(pwd -P) != "$repo_dir" ]]; then
  echo "Run this script from $repo_dir"
  exit 1
fi

# === config that goes in ~/.config
config_dir="$HOME/.config"
mkdir -p "$config_dir"
pushd "$config_dir"

ln -s ../.dotfiles/config/ghostty ./
ln -s ../.dotfiles/config/neofetch ./
ln -s ../.dotfiles/config/ranger ./

popd

# === config that goes in ~
pushd "$HOME"

ln -s .dotfiles/git/.gitconfig ./
ln -s .dotfiles/git/.gitignore_global ./
ln -s .dotfiles/vim/.vimrc ./
ln -s .dotfiles/tig/.tigrc ./

popd


# === config that goes in ~/.local/share
# Konsole doesn't like symlinks
mkdir -p "$HOME/.local/share/color-schemes/"
mkdir -p "$HOME/.local/share/konsole"

cp local/share/color-schemes/GruvboxColors.colors "$HOME/.local/share/color-schemes/GruvboxColors.colors"
cp local/share/konsole/xero.profile "$HOME/.local/share/konsole/xero.profile"
cp local/share/konsole/Gruvbox.colorscheme "$HOME/.local/share/konsole/Gruvbox.colorscheme"


echo "Setup complete ^_^"